import { Router } from 'express';
import axios from 'axios';
import pg from 'pg';
const router = Router();
const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });

const VANNA_API_URL = process.env.VANNA_API_BASE_URL || 'http://localhost:8000';

router.post('/', async (req, res) => {
  const { query } = req.body;
  if (!query) {
    return res.status(400).json({ error: 'query required' });
  }

  try {
    // Call Vanna AI service to generate SQL
    const vannaResponse = await axios.post(
      `${VANNA_API_URL}/nl-to-sql`,
      {
        query,
        max_rows: 200
      },
      {
        timeout: 30000,
        headers: {
          'Content-Type': 'application/json'
        }
      }
    );

    // Validate response structure
    if (!vannaResponse.data) {
      throw new Error('Empty response from AI service');
    }

    const { sql, rows, columns, total_rows } = vannaResponse.data;
    
    // Validate that we have the required data
    if (!sql) {
      throw new Error('No SQL generated by AI service');
    }

    // Ensure rows is an array
    const resultRows = Array.isArray(rows) ? rows : [];
    
    // Return the AI-generated results
    res.json({ 
      sql, 
      rows: resultRows,
      columns: columns || (resultRows.length > 0 ? Object.keys(resultRows[0]) : []),
      total_rows: total_rows || resultRows.length,
      answer: `AI Analysis: Found ${resultRows.length} results for your query: "${query}"`,
      interpretation: `Generated SQL using GROQ AI: ${sql}`,
      ai_powered: true
    });
  } catch (err: any) {
    console.error('Chat error:', {
      message: err.message,
      code: err.code,
      response: err.response?.data,
      status: err.response?.status,
      stack: err.stack
    });
    
    // Handle different types of errors
    if (err.code === 'ECONNREFUSED' || err.code === 'ETIMEDOUT') {
      return res.status(503).json({ 
        error: 'AI service unavailable',
        details: 'The Vanna AI service is not running or not reachable. Please ensure it is started with: cd apps/vanna && uvicorn main:app --reload --port 8000',
        code: err.code
      });
    }
    
    if (err.response) {
      // Vanna service returned an error response
      const statusCode = err.response.status || 500;
      const errorMessage = err.response.data?.detail || err.response.data?.error || err.message || 'Failed to process query';
      
      return res.status(statusCode).json({ 
        error: errorMessage,
        details: err.response.data?.message || 'AI service returned an error. Please try rephrasing your question.',
        code: err.code
      });
    }
    
    // Generic error
    res.status(500).json({ 
      error: err.message || 'Failed to process query',
      details: 'An unexpected error occurred. Please check if the Vanna AI service is running and try again.',
      code: err.code
    });
  }
});

export default router;
